# Alacritty
[".local/share/alacritty/catppuccin.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "24h"

# Bat
[".config/bat/themes/catppuccin.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin Mocha.tmTheme"
refreshPeriod = "24h"

# Delta
[".config/bat/themes/catppuccin.gitconfig"]
type = "file"
url = "https://github.com/catppuccin/delta/raw/main/catppuccin.gitconfig"
refreshPeriod = "24h"

# Eza
[".config/eza/theme.yml"]
type = "file"
url = "https://github.com/eza-community/eza-themes/raw/main/themes/catppuccin.yml"
refreshPeriod = "24h"

# K9s
[".config/k9s/skins"]
type = "archive"
url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "24h"

# LazyVim
[".config/nvim/init.lua"]
type = "file"
url = "https://github.com/LazyVim/starter/raw/main/init.lua"
refreshPeriod = "24h"

# Xcode
["Library/Developer/Xcode/UserData/FontAndColorThemes/Catppuccin Mocha.xccolortheme"]
type = "file"
url = "https://github.com/catppuccin/xcode/raw/main/themes/Catppuccin Mocha.xccolortheme"
refreshPeriod = "24h"

# Zellij
[".local/share/zellij/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm"
refreshPeriod = "24h"
