# Bat
[".config/bat/themes/catppuccin.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin Mocha.tmTheme"
refreshPeriod = "24h"

# btop
[".config/btop/themes/catppuccin_mocha.theme"]
type = "file"
url = "https://github.com/catppuccin/btop/raw/main/themes/catppuccin_mocha.theme"
refreshPeriod = "24h"

# Delta
[".config/bat/themes/catppuccin.gitconfig"]
type = "file"
url = "https://github.com/catppuccin/delta/raw/main/catppuccin.gitconfig"
refreshPeriod = "24h"

# Eza
[".config/eza/theme.yml"]
type = "file"
url = "https://github.com/eza-community/eza-themes/raw/main/themes/catppuccin.yml"
refreshPeriod = "24h"

# K9s
[".config/k9s/skins"]
type = "archive"
url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "24h"

# LazyVim
[".config/nvim/init.lua"]
type = "file"
url = "https://github.com/LazyVim/starter/raw/main/init.lua"
refreshPeriod = "24h"

# Xcode
["Library/Developer/Xcode/UserData/FontAndColorThemes/Catppuccin Mocha.xccolortheme"]
type = "file"
url = "https://github.com/catppuccin/xcode/raw/main/themes/Catppuccin Mocha.xccolortheme"
refreshPeriod = "24h"

# Yazi
[".config/yazi/plugins/miller.yazi"]
type = "archive"
url = "https://github.com/AnirudhG07/miller.yazi/archive/patch-1.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "24h"

[".config/yazi/plugins/yatline-catppuccin.yazi"]
type = "archive"
url = "https://github.com/imsi32/yatline-catppuccin.yazi/archive/main.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "24h"

# Zellij
[".local/share/zellij/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm"
refreshPeriod = "24h"
