# Alacritty
[".local/share/alacritty/catppuccin.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "24h"

# Nushell
[".local/share/nushell/catppuccin.nu"]
type = "file"
url = "https://github.com/nik-rev/catppuccin-nushell/raw/main/themes/catppuccin_mocha.nu"
refreshPeriod = "24h"

[".local/share/nushell/nu_scripts"]
type = "git-repo"
url = "https://github.com/nushell/nu_scripts"
refreshPeriod = "24h"

# K9s
[".config/k9s/skins"]
type = "archive"
url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "24h"

# Zellij
[".local/share/zellij/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm"
refreshPeriod = "24h"
