[".local/share/alacritty/catppuccin.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "24h"

[".config/k9s/skins"]
type = "archive"
url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "24h"


[".local/share/nushell/catppuccin.nu"]
type = "file"
url = "https://github.com/nik-rev/catppuccin-nushell/raw/main/themes/catppuccin_mocha.nu"
refreshPeriod = "24h"
