[".antidote"]
type = "archive"
url = "https://github.com/mattmc3/antidote/archive/main.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "24h"

[".config/k9s/skins"]
type = "archive"
url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "24h"

[".config/alacritty/catppuccin-mocha.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "24h"
