- clean: ['~']

- shell:
    - [git submodule update, Updating dotbot]
    - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.vim:
        force: true
        relink: true
        path: vim
    ~/.vimrc:
        force: true
        relink: true
        path: vimrc
    ~/.htoprc:
        force: true
        relink: true
        path: htoprc
    ~/.npmrc:
        force: true
        relink: true
        path: npmrc
    ~/.gitconfig:
        force: true
        relink: true
        path: gitconfig
    ~/.gitignore:
        force: true
        relink: true
        path: gitignore
    ~/.tmux.conf:
        force: true
        relink: true
        path: tmux.conf
    ~/.tmux/plugins/tpm:
        create: true
        force: true
        relink: true
        path: tpm
    ~/.tmuxinator:
        force: true
        relink: true
        path: tmuxinator
    ~/.zshrc:
        force: true
        relink: true
        path: zshrc
    ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme:
        create: true
        force: true
        relink: true
        path: spaceship/spaceship.zsh-theme
    ~/.oh-my-zsh/custom/plugins/aliases/aliases.plugin.zsh:
        create: true
        force: true
        relink: true
        path: oh-my-zsh/plugins/aliases/aliases.plugin.zsh
    ~/.oh-my-zsh/custom/plugins/dirs/dirs.plugin.zsh:
        create: true
        force: true
        relink: true
        path: oh-my-zsh/plugins/dirs/dirs.plugin.zsh
