- clean: ['~']

- shell:
    - [git submodule update, Updating dotbot]
    - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.SpaceVim:
        force: true
        relink: true
        path: SpaceVim
    ~/.vim:
        force: true
        relink: true
        path: SpaceVim
    ~/.cache/vimfiles/repos/github.com/Shougo/dein.vim:
        create: true
        force: true
        relink: true
        path: dein.vim
    ~/.SpaceVim.d:
        force: true
        relink: true
        path: SpaceVim.d
    ~/.htoprc:
        force: true
        relink: true
        path: htoprc
    ~/.gemrc:
        force: true
        relink: true
        path: gemrc
    ~/.irbrc:
        force: true
        relink: true
        path: irbrc
    ~/.npmrc:
        force: true
        relink: true
        path: npmrc
    ~/.gitconfig:
        force: true
        relink: true
        path: gitconfig
    ~/.gitignore:
        force: true
        relink: true
        path: gitignore
    ~/.zshrc:
        force: true
        relink: true
        path: zshrc
    ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme:
        create: true
        force: true
        relink: true
        path: spaceship/spaceship.zsh-theme
    ~/.oh-my-zsh/custom/plugins/aliases/aliases.plugin.zsh:
        create: true
        force: true
        relink: true
        path: oh-my-zsh/plugins/aliases/aliases.plugin.zsh
    ~/.oh-my-zsh/custom/plugins/dirs/dirs.plugin.zsh:
        create: true
        force: true
        relink: true
        path: oh-my-zsh/plugins/dirs/dirs.plugin.zsh
