- clean: ['~']

- shell:
    - [git submodule update, Updating dotbot]
    - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.asdfrc:
        force: true
        relink: true
        path: asdfrc
    ~/.brewfile:
        force: true
        relink: true
        path: brewfile
    ~/.default-gems:
        force: true
        relink: true
        path: default-gems
    ~/.gemrc:
        force: true
        relink: true
        path: gemrc
    ~/.gitconfig:
        force: true
        relink: true
        path: gitconfig
    ~/.gitignore:
        force: true
        relink: true
        path: gitignore
    ~/.gnupg/gpg.conf:
        force: true
        relink: true
        path: gpg.conf
    ~/.htoprc:
        force: true
        relink: true
        path: htoprc
    ~/.irbrc:
        force: true
        relink: true
        path: irbrc
    ~/.itermocil:
        force: true
        relink: true
        path: itermocil
    ~/.npmrc:
        force: true
        relink: true
        path: npmrc
    ~/.oh-my-zsh/custom/plugins/aliases/aliases.plugin.zsh:
        create: true
        force: true
        relink: true
        path: oh-my-zsh/plugins/aliases/aliases.plugin.zsh
    ~/.oh-my-zsh/custom/plugins/dirs/dirs.plugin.zsh:
        create: true
        force: true
        relink: true
        path: oh-my-zsh/plugins/dirs/dirs.plugin.zsh
    ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme:
        create: true
        force: true
        relink: true
        path: spaceship/spaceship.zsh-theme
    ~/.zshrc:
        force: true
        relink: true
        path: zshrc
