# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)"        # For use with zsh-vi-mode

[directory]
truncation_length = 4
style = 'bold lavender'
read_only = ' 󰌾'
[directory.substitutions]
"Desktop" = "󰇄 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '  '
[aws.region_aliases]
us-east-2 = 'main'
[aws.profile_aliases]
default = 'GLS'

[azure]
disabled = true

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[buf]
disabled = true

[bun]
disabled = true

[c]
symbol = ' '

[cmake]
symbol = ' '

[cobol]
disabled = true

[conda]
symbol = ' '

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[docker_context]
symbol = ' '

[dotnet]
disabled = true

[elixir]
symbol = ' '

[elm]
disabled = true

[fennel]
disabled = true

[git_branch]
style = 'bold mauve'
symbol = ' '

[git_commit]
tag_symbol = '  '

[git_metrics]
disabled = false

[gleam]
disabled = true

[golang]
symbol = ' '

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[hostname]
ssh_symbol = ' '

[java]
symbol = ' '

[julia]
disabled = true

[kotlin]
symbol = ' '

[kubernetes]
disabled = false
detect_folders = ["$HOME/Code"]

[[kubernetes.contexts]]
context_pattern = 'production'
style = 'bold red'
context_alias = 'prod'

[[kubernetes.contexts]]
context_pattern = 'staging'
style = 'bold yellow'
context_alias = 'stag'

[lua]
symbol = ' '

[memory_usage]
disabled = false
symbol = '󰍛 '

[meson]
disabled = true

[mojo]
disabled = true

[nats]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
symbol = ' '

[ocaml]
disabled = true

[odin]
disabled = true

[openstack]
disabled = true

[os.symbols]
Alpaquita = ' '
Alpine = ' '
AlmaLinux = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CachyOS = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Kali = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
Nobara = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
RockyLinux = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Void = ' '
Windows = '󰍲 '

[package]
symbol = '󰏗 '

[perl]
symbol = ' '

[php]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
symbol = ' '

[quarto]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rust]
disabled = true
symbol = '󱘗 '

[ruby]
symbol = ' '

[scala]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = false

[sudo]
disabled = false

[swift]
symbol = ' '

[time]
disabled = false

[typst]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
