#!/usr/bin/env bash
# shellcheck disable=SC1091

source "$HOME/.config/sketchybar/colors.sh"
# TODO: Test dynamic island plugin
# source "$HOME/.config/sketchybar/userconfig.sh" # Loads all defined variables

# Directories
PLUGINS_DIR="$HOME/.config/sketchybar/plugins"

FONT="CaskaydiaMono Nerd Font Mono"
ICON_PADDING=8
LABEL_PADDING=0
BACKGROUND_PADDING=4

bar_config=(
  color="$BAR_COLOR"
  height=30
  padding_left=16
  padding_right=16
)

icon_defaults=(
  icon.color="$ICON_COLOR"
  icon.font="$FONT:Bold:16.0"
  icon.padding_left="$ICON_PADDING"
  icon.padding_right="$ICON_PADDING"
)

label_defaults=(
  label.color="$TEXT"
  label.font="$FONT:Bold:12.0"
  label.padding_left="$LABEL_PADDING"
  label.padding_right="$LABEL_PADDING"
)

background_defaults=(
  background.corner_radius=4
  background.height=20
  background.color="$SURFACE0"
  background.padding_left="$BACKGROUND_PADDING"
  background.padding_right="$BACKGROUND_PADDING"
  background.drawing=off
)

popup_defaults=(
  popup.horizontal=false
  popup.background.border_color="$BLUE"
  popup.background.border_width=2
  popup.background.color="$BASE"
  popup.background.corner_radius=4
  popup.background.shadow.drawing=on
)

sketchybar --bar "${bar_config[@]}" \
  --default \
  updates=when_shown \
  "${icon_defaults[@]}" \
  "${label_defaults[@]}" \
  "${background_defaults[@]}" \
  "${popup_defaults[@]}"

sketchybar --hotload true

# Left items
source "$PLUGINS_DIR/apple/item.sh"
source "$PLUGINS_DIR/applications/item.sh"

# Right items
source "$PLUGINS_DIR/battery/item.sh"
source "$PLUGINS_DIR/calendar/item.sh"
source "$PLUGINS_DIR/network/item.sh"
source "$PLUGINS_DIR/memory/item.sh"
source "$PLUGINS_DIR/cpu/item.sh"
source "$PLUGINS_DIR/menu_items/item.sh"
source "$PLUGINS_DIR/spaces/item.sh"

sketchybar --update
