[settings]
activate_aggressive = true
plugin_autoupdate_last_check_duration = '1 day'

[tools]
"asdf:neovim" = 'nightly'
elixir = '1.18'
erlang = '27'
golang = '1.24'
helm = 'latest'
kubectl = 'latest'
lazydocker = 'latest'
lua = '5.1'
node = 'lts'
opentofu = 'latest'
perl = { version = '5.40.1', postinstall = 'cpanm Neovim::Ext' }
python = '3.12'
rebar = '3'
ruby = '3.3'
rust = '1.85'
uv = 'latest'
