[settings]
activate_aggressive = true
plugin_autoupdate_last_check_duration = '1 day'

[tasks.chezmoi]
alias = 'c'
description = 'Apply chezmoi changes'
run = "chezmoi apply"

[tools]
"asdf:neovim" = 'nightly'
elixir = '1.18'
erlang = '27'
golang = '1.24'
helm = '3'
lua = '5.1'
node = '22'
opentofu = '1.9'
perl = { version = '5.40', postinstall = 'cpanm Neovim::Ext' }
python = '3.12'
rebar = '3.24'
ruby = '3.3'
rust = '1.85'
uv = { version = 'latest', postinstall = 'uv tool install posting' }
