[manager]
linemode = "mtime"
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true

[preview]
tab_size = 2
max_width = 2000
max_height = 1200
wrap = "yes"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[plugin]
prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },

  # csv
  { mime = "text/csv", run = "miller" },

  # Eza
  { name = "*/", run = "eza-preview" },

  # Markdown
  { name = "*.md", run = "glow" },
]
